name: CI - Dockerized Appication Verify
on:
  workflow_call:
    inputs:
      organization:
        required: true
        type: string
      repository:
        required: true
        type: string
      app:
        required: true
        type: string
      version:
        required: true
        type: string
    secrets:
      ecr-iam-role:
        description: "ECR IAM role arn"
        required: true
      secret-outputs-passphrase:
        description: "Passphrase for secret outputs"
        required: true
      registry:
        description: "Docker registry"
        required: true
    outputs:
      image:
        description: "Docker Image"
        value: ${{ jobs.pull.outputs.image }}
      tag:
        description: "Docker image tag"
        value: ${{ jobs.pull.outputs.tag }}

permissions:
  id-token: write
  contents: read

jobs:
  pull:
    runs-on: ["self-hosted"]
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          aws-region: us-west-2
          role-to-assume: ${{ secrets.ecr-iam-role }}

      - uses: cloudposse/github-action-docker-image-exists@0.1.0
        id: pull
        with:
          organization: ${{ inputs.organization }}
          repository: ${{ inputs.repository }}/${{ inputs.app }}
          registry: ${{ secrets.registry }}
          tag: ${{ inputs.version }}

      - uses: cloudposse/github-action-secret-outputs@0.1.0
        id: image
        with:
          secret: ${{ secrets.secret-outputs-passphrase }}
          op: encode
          in: ${{ steps.pull.outputs.image }}

    outputs:
      image: ${{ steps.image.outputs.out }}
      tag: ${{ steps.pull.outputs.tag }}
