name: CI - Dockerized Appication Build
on:
  workflow_call:
    inputs:
      organization:
        required: true
        type: string
      repository:
        required: true
        type: string
      app:
        required: true
        type: string
      force-build:
        required: true
        type: boolean
      matrix-step-name:
        required: false
        type: string
      matrix-key:
        required: false
        type: string
    secrets:
      ecr-iam-role:
        description: "ECR IAM role arn"
        required: true
      secret-outputs-passphrase:
        description: "Passphrase for secret outputs"
        required: true
      registry:
        description: "Docker registry"
        required: true
    outputs:
      image:
        description: "Docker Image"
        value: ${{ jobs.promote-or-build.outputs.image }}
      tag:
        description: "Docker image tag"
        value: ${{ jobs.promote-or-build.outputs.tag }}

permissions:
  id-token: write
  contents: read

jobs:
  validate:
    name: validate deploy file
    runs-on: ["self-hosted"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate
        id: validate
        uses: cardinalby/schema-validator-action@v1
        with:
          file: ./apps/${{ inputs.app }}/deploy.yaml
          schema: ./.github/configs/deploy.schema.json

  promote-or-build:
    name: promote or build
    runs-on: ["self-hosted"]
    needs: [ validate ]
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          aws-region: us-west-2
          role-to-assume: ${{ secrets.ecr-iam-role }}

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Get previous commit
        if: ${{ ! inputs.force-build }}
        id: prev-commit
        run: echo "sha=$(git rev-parse --verify HEAD^1)" >> $GITHUB_OUTPUT

      - uses: cloudposse/github-action-docker-promote@0.1.0
        if: ${{ ! inputs.force-build }}
        id: promote
        continue-on-error: true
        with:
          registry: ${{ secrets.registry }}
          organization: ${{ inputs.organization }}
          repository: ${{ inputs.repository }}/${{ inputs.app }}
          from: sha-${{ steps.prev-commit.outputs.sha }}
          to: sha-${{ github.sha }}
          use_metadata: true

      - name: Build
        if: ${{ inputs.force-build || steps.promote.outcome == 'failure' }}
        id: build
        uses: cloudposse/github-action-docker-build-push@1.6.0
        with:
          organization: ${{ inputs.organization }}
          repository: ${{ inputs.repository }}/${{ inputs.app }}
          registry: ${{ secrets.registry }}
          workdir: ./apps/${{ inputs.app }}

      - uses: cloudposse/github-action-yaml-config-query@0.1.0
        id: result
        with:
          ## There is a bug in GHA - skipped step return `success` outcome. So we can not rely only on steps.build.outcome
          query: .${{ steps.build.outcome == 'success' && ( inputs.force-build || steps.promote.outcome == 'failure' ) }}
          config: |-
            true:
              builded: true
              image: ${{ steps.build.outputs.image }}
              tag: ${{ steps.build.outputs.tag }}
            false:
              builded: false
              image: ${{ steps.promote.outputs.image }}
              tag: ${{ steps.promote.outputs.tag }}

      - uses: cloudposse/github-action-secret-outputs@0.1.0
        id: image
        with:
          secret: ${{ secrets.secret-outputs-passphrase }}
          op: encode
          in: ${{ steps.result.outputs.image }}

      - uses: cloudposse/github-action-matrix-outputs-write@0.3.0
        id: outputs
        with:
          matrix-step-name: ${{ inputs.matrix-step-name }}
          matrix-key: ${{ inputs.matrix-key }}
          outputs: |
            image: ${{ steps.image.outputs.out }}
            tag: ${{ steps.result.outputs.tag }}            


    outputs:
      builded: ${{ steps.result.outputs.builded }}
      image: ${{ fromJson(steps.outputs.outputs.result).image }}
      tag: ${{ fromJson(steps.outputs.outputs.result).tag }}

  test:
    runs-on: ["self-hosted"]
    if: ${{ needs.promote-or-build.outputs.builded == 'true' }}
    needs: [ promote-or-build ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Tests
        id: test
        uses: cloudposse/github-action-docker-compose-test-run@0.1.2
        with:
          workdir: ./apps/${{ inputs.app }}
          file: test/docker-compose.yml
          service: app
          command: test/test.sh
          registry: ${{ secrets.registry }}

