name: Draft release
on:
  workflow_call:
    secrets:
      github-private-actions-pat:
        required: true
jobs:
  draft:
    runs-on: [ "self-hosted" ]
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "master"
      - name: Create/Update Draft release
        uses: release-drafter/release-drafter@v5
        with:
          publish: false
          prerelease: false
          config-name: configs/draft-release.yml
        env:
          GITHUB_TOKEN: ${{ secrets.github-private-actions-pat }}
