name: Create Release branch
on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
    secrets:
      github-private-actions-pat:
        required: true
jobs:
  release-branch:
    runs-on: ["self-hosted"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create branch for specific version
        uses: satya-500/create-branch-from-tag@v1.0
        env:
          GITHUB_TOKEN: ${{ secrets.github-private-actions-pat }}
        with:
          branch: release/${{ inputs.version }}
          from: tags/${{ inputs.version }}

