name: Dockerized Appication - Hotfix release
on:
  workflow_call:
    inputs:
      organization:
        required: true
        type: string
      repository:
        required: true
        type: string
      apps:
        required: true
        type: string
      contains_changes:
        required: true
        type: string
      default_branch:
        description: "Default branch in the repo"
        required: true
        type: string
        default: main
    secrets:
      ecr-iam-role:
        description: "ECR IAM role arn"
        required: true
      secret-outputs-passphrase:
        description: "Passphrase for secret outputs"
        required: true
      registry:
        description: "Docker registry"
        required: true
      github-private-actions-pat:
        required: true

permissions:
  contents: write
  id-token: write

jobs:
  ci:
    uses: vstreaminc/github-action-workflows/.github/workflows/ci-dockerized-app-build.yml@main
    if: ${{ inputs.apps != '[]'  }}
    strategy:
      matrix:
        app: ${{ fromJson(inputs.apps) }}
    with:
      organization: ${{ inputs.organization }}
      repository: ${{ inputs.repository }}
      app: ${{ matrix.app }}
      force-build: ${{ contains(fromJson(inputs.contains_changes), matrix.app) }}
    secrets:
      ecr-iam-role: ${{ secrets.ecr-iam-role }}
      registry: "${{ secrets.registry }}"
      secret-outputs-passphrase: "${{ secrets.secret-outputs-passphrase }}"

  release:
    needs: [ci]
    uses: vstreaminc/github-action-workflows/.github/workflows/controller-hotfix-release.yml@main
    with:
      ref: ${{ github.sha }}

  promote:
    needs: [release]
    uses: vstreaminc/github-action-workflows/.github/workflows/ci-dockerized-app-promote.yml@main
    if: ${{ inputs.apps != '[]'  }}
    strategy:
      matrix:
        app: ${{ fromJson(inputs.apps) }}
    with:
      organization: ${{ inputs.organization }}
      repository: ${{ inputs.repository }}
      app: ${{ matrix.app }}
      version: ${{ needs.release.outputs.version }}
    secrets:
      ecr-iam-role: ${{ secrets.ecr-iam-role }}
      registry: "${{ secrets.registry }}"
      secret-outputs-passphrase: "${{ secrets.secret-outputs-passphrase }}"

  reintegrate:
    uses: vstreaminc/github-action-workflows/.github/workflows/controller-hotfix-reintegrate.yml@main
    needs: [promote]
    with:
      ref: ${{ github.ref }}
      target_branch: ${{ inputs.default_branch }}
    secrets:
      github-private-actions-pat: "${{ secrets.github-private-actions-pat }}"


